version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdb
    ports:
      - "5436:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  microservicio-client:
    build: ./microservicio-client
    container_name: microservicio-client
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5436/db_ms_client
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8081:8081"

  microservicio-movements:
    build: ./microservicio-movements
    container_name: microservicio-movements
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5436/db_ms_movement
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8082:8082"

volumes:
  postgres-data:
