--
-- PostgreSQL database dump
--

-- Dumped from database version 13.15 (Debian 13.15-1.pgdg120+1)
-- Dumped by pg_dump version 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS db_ms_movement;
--
-- Name: db_ms_movement; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE db_ms_movement WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.utf8';


ALTER DATABASE db_ms_movement OWNER TO postgres;

\connect db_ms_movement

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: dbo; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA dbo;


ALTER SCHEMA dbo OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account; Type: TABLE; Schema: dbo; Owner: postgres
--

CREATE TABLE dbo.account (
    account_id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    modified_by character varying(255),
    modified_date timestamp(6) without time zone,
    account_number character varying(255),
    account_type character varying(255),
    balance character varying(255),
    client_id bigint,
    status boolean
);


ALTER TABLE dbo.account OWNER TO postgres;

--
-- Name: account_account_id_seq; Type: SEQUENCE; Schema: dbo; Owner: postgres
--

ALTER TABLE dbo.account ALTER COLUMN account_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dbo.account_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movement; Type: TABLE; Schema: dbo; Owner: postgres
--

CREATE TABLE dbo.movement (
    movement_id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    modified_by character varying(255),
    modified_date timestamp(6) without time zone,
    account_id bigint,
    balance numeric(38,2),
    movement_date timestamp(6) without time zone,
    movement_type character varying(255),
    value numeric(38,2),
    initial_balance numeric(38,2)
);


ALTER TABLE dbo.movement OWNER TO postgres;

--
-- Name: movement_movement_id_seq; Type: SEQUENCE; Schema: dbo; Owner: postgres
--

ALTER TABLE dbo.movement ALTER COLUMN movement_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dbo.movement_movement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: account; Type: TABLE DATA; Schema: dbo; Owner: postgres
--

INSERT INTO dbo.account (account_id, created_by, created_date, modified_by, modified_date, account_number, account_type, balance, client_id, status) VALUES (1, NULL, '2025-02-14 09:07:14.735025', NULL, '2025-02-14 09:58:05.283221', '123123213', 'AHO', '1977.00', 1, true);
INSERT INTO dbo.account (account_id, created_by, created_date, modified_by, modified_date, account_number, account_type, balance, client_id, status) VALUES (3, NULL, '2025-02-14 11:12:34.901979', NULL, '2025-02-14 11:14:39.435674', '123123215', 'CRR', '6.00', 2, true);
INSERT INTO dbo.account (account_id, created_by, created_date, modified_by, modified_date, account_number, account_type, balance, client_id, status) VALUES (2, NULL, '2025-02-14 10:06:32.990601', NULL, '2025-02-14 11:16:10.326307', '123123214', 'AHO', '3.00', 2, true);


--
-- Data for Name: movement; Type: TABLE DATA; Schema: dbo; Owner: postgres
--

INSERT INTO dbo.movement (movement_id, created_by, created_date, modified_by, modified_date, account_id, balance, movement_date, movement_type, value, initial_balance) VALUES (9, NULL, '2025-02-14 09:55:02.718756', NULL, NULL, 1, 1977.00, '2025-02-14 09:55:02.715668', 'RETIRO de 23.00', -23.00, 2000.00);
INSERT INTO dbo.movement (movement_id, created_by, created_date, modified_by, modified_date, account_id, balance, movement_date, movement_type, value, initial_balance) VALUES (10, NULL, '2025-02-14 09:56:27.978999', NULL, NULL, 1, 1974.00, '2025-02-14 09:56:27.976332', 'RETIRO de 3.00', -3.00, 1977.00);
INSERT INTO dbo.movement (movement_id, created_by, created_date, modified_by, modified_date, account_id, balance, movement_date, movement_type, value, initial_balance) VALUES (11, NULL, '2025-02-14 09:58:05.288586', NULL, NULL, 1, 1977.00, '2025-02-14 09:58:05.288139', 'DEPOSITO de 3.00', 3.00, 1974.00);
INSERT INTO dbo.movement (movement_id, created_by, created_date, modified_by, modified_date, account_id, balance, movement_date, movement_type, value, initial_balance) VALUES (12, NULL, '2025-02-14 11:14:29.653995', NULL, NULL, 3, 3.00, '2025-02-14 11:14:29.65204', 'DEPOSITO de 3.00', 3.00, 0.00);
INSERT INTO dbo.movement (movement_id, created_by, created_date, modified_by, modified_date, account_id, balance, movement_date, movement_type, value, initial_balance) VALUES (13, NULL, '2025-02-14 11:14:39.440828', NULL, NULL, 3, 6.00, '2025-02-14 11:14:39.44031', 'DEPOSITO de 3.00', 3.00, 3.00);
INSERT INTO dbo.movement (movement_id, created_by, created_date, modified_by, modified_date, account_id, balance, movement_date, movement_type, value, initial_balance) VALUES (14, NULL, '2025-02-14 11:16:10.333998', NULL, NULL, 2, 3.00, '2025-02-14 11:16:10.333548', 'DEPOSITO de 3.00', 3.00, 0.00);


--
-- Name: account_account_id_seq; Type: SEQUENCE SET; Schema: dbo; Owner: postgres
--

SELECT pg_catalog.setval('dbo.account_account_id_seq', 3, true);


--
-- Name: movement_movement_id_seq; Type: SEQUENCE SET; Schema: dbo; Owner: postgres
--

SELECT pg_catalog.setval('dbo.movement_movement_id_seq', 14, true);


--
-- Name: account account_pkey; Type: CONSTRAINT; Schema: dbo; Owner: postgres
--

ALTER TABLE ONLY dbo.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (account_id);


--
-- Name: movement movement_pkey; Type: CONSTRAINT; Schema: dbo; Owner: postgres
--

ALTER TABLE ONLY dbo.movement
    ADD CONSTRAINT movement_pkey PRIMARY KEY (movement_id);


--
-- Name: account uk66gkcp94endmotfwb8r4ocxm9; Type: CONSTRAINT; Schema: dbo; Owner: postgres
--

ALTER TABLE ONLY dbo.account
    ADD CONSTRAINT uk66gkcp94endmotfwb8r4ocxm9 UNIQUE (account_number);


--
-- Name: account_number_client_id_idx; Type: INDEX; Schema: dbo; Owner: postgres
--

CREATE INDEX account_number_client_id_idx ON dbo.account USING btree (account_number, client_id);


--
-- PostgreSQL database dump complete
--

