--
-- PostgreSQL database dump
--

-- Dumped from database version 13.15 (Debian 13.15-1.pgdg120+1)
-- Dumped by pg_dump version 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS db_ms_client;
--
-- Name: db_ms_client; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE db_ms_client WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.utf8';


ALTER DATABASE db_ms_client OWNER TO postgres;

\connect db_ms_client

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: dbo; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA dbo;


ALTER SCHEMA dbo OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: client; Type: TABLE; Schema: dbo; Owner: postgres
--

CREATE TABLE dbo.client (
    client_id bigint NOT NULL,
    created_by character varying(255),
    created_date timestamp(6) without time zone,
    modified_by character varying(255),
    modified_date timestamp(6) without time zone,
    address character varying(255),
    birthday date,
    gender character varying(255),
    identifier character varying(255),
    name character varying(255),
    phone character varying(255),
    password character varying(255),
    status boolean
);


ALTER TABLE dbo.client OWNER TO postgres;

--
-- Name: client_client_id_seq; Type: SEQUENCE; Schema: dbo; Owner: postgres
--

ALTER TABLE dbo.client ALTER COLUMN client_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dbo.client_client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: client; Type: TABLE DATA; Schema: dbo; Owner: postgres
--

INSERT INTO dbo.client (client_id, created_by, created_date, modified_by, modified_date, address, birthday, gender, identifier, name, phone, password, status) VALUES (1, NULL, '2025-02-14 08:49:38.735525', NULL, NULL, '13 junio y Equinoccial', '1998-11-05', 'M', '0102345003', 'Juan Osorio', '098874587 ', '1245', true);
INSERT INTO dbo.client (client_id, created_by, created_date, modified_by, modified_date, address, birthday, gender, identifier, name, phone, password, status) VALUES (2, NULL, '2025-02-14 10:04:45.761976', NULL, NULL, '13 junio y Equinoccial', '1998-11-05', 'M', '0102345004', 'Juan Osorio 2', '098874587 ', '1245', true);


--
-- Name: client_client_id_seq; Type: SEQUENCE SET; Schema: dbo; Owner: postgres
--

SELECT pg_catalog.setval('dbo.client_client_id_seq', 2, true);


--
-- Name: client client_pkey; Type: CONSTRAINT; Schema: dbo; Owner: postgres
--

ALTER TABLE ONLY dbo.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (client_id);


--
-- Name: client uk8qsnpqt81w3nuqk3ug32yq7hs; Type: CONSTRAINT; Schema: dbo; Owner: postgres
--

ALTER TABLE ONLY dbo.client
    ADD CONSTRAINT uk8qsnpqt81w3nuqk3ug32yq7hs UNIQUE (identifier);


--
-- PostgreSQL database dump complete
--

